basePath: /api/v1
definitions:
  model.Album:
    properties:
      artist:
        type: string
      id:
        description: 'Note: swaggerignore:"true"'
        type: string
      price:
        type: number
      title:
        type: string
      url:
        type: string
    type: object
externalDocs:
  description: Swaggo
  url: https://github.com/swaggo/swag
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Album API Doc.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Album APIs
  version: "1.0"
paths:
  /album:
    get:
      consumes:
      - multipart/form-data
      description: Get The List Of Albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Album'
            type: array
      summary: Get All Albums
      tags:
      - Album
    post:
      consumes:
      - application/json
      description: Create An Album
      parameters:
      - description: Album Data
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/model.Album'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Album'
      security:
      - JWT: []
      summary: Create Album
      tags:
      - Album
  /album/{id}:
    get:
      description: Get An Album By Id
      parameters:
      - description: Album Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Album'
      security:
      - JWT: []
      summary: Get Album
      tags:
      - Album
schemes:
- http
- https
securityDefinitions:
  JWT:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
